// a simple function that appends "Hello, "
// to the beginning of the argument

//fn myfunction1(name) {
//    return "Dear, " + name;
//}

fn myfunction2(name) {
    return "Rachel, " + name;
}

// Rhai return the value of the last expression
// myfunction1("World!");

// Rhai return the value of the last expression
myfunction2("Green");

// For demonstration replace this entire contents contents of 
// for1_01.rhai and the application will do something different.


